### ISSUE TITLE
Remove PDF from source control

### ISSUE THREAD

**Issue by debber1** [woutlyen/Global-Challenges#1]
Currently, the addition of the compiled PDF to source control makes it so merge conflicts will be more difficult to solve when a PR gets made. The solution is to just untrack the PDF  and add it to the .gitignore.

**Comment by woutlyen** [comment]
solved in [550eb03](https://github.com/woutlyen/Global-Challenges/commit/550eb03b6bd604b6445b405b21c2ca2ffee86b94)
